/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsShopIdRouteImport } from './routes/shops/$shopId'
import { Route as SettingsOrganizationsRouteImport } from './routes/settings/organizations'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as ReportsRevenueRouteImport } from './routes/reports/revenue'
import { Route as ReportsCustomersRouteImport } from './routes/reports/customers'
import { Route as ReportsChurnRouteImport } from './routes/reports/churn'
import { Route as ReportsAppStoreRouteImport } from './routes/reports/app-store'
import { Route as JobsSplatRouteImport } from './routes/jobs/$'
import { Route as AppsAppIdRouteImport } from './routes/apps/$appId'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGoogleAnalyticsOauthStartRouteImport } from './routes/api/google-analytics/oauth/start'
import { Route as ApiGoogleAnalyticsOauthCallbackRouteImport } from './routes/api/google-analytics/oauth/callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrganizationsRoute = SettingsOrganizationsRouteImport.update({
  id: '/settings/organizations',
  path: '/settings/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRevenueRoute = ReportsRevenueRouteImport.update({
  id: '/reports/revenue',
  path: '/reports/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCustomersRoute = ReportsCustomersRouteImport.update({
  id: '/reports/customers',
  path: '/reports/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsChurnRoute = ReportsChurnRouteImport.update({
  id: '/reports/churn',
  path: '/reports/churn',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAppStoreRoute = ReportsAppStoreRouteImport.update({
  id: '/reports/app-store',
  path: '/reports/app-store',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSplatRoute = JobsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => JobsRoute,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleAnalyticsOauthStartRoute =
  ApiGoogleAnalyticsOauthStartRouteImport.update({
    id: '/api/google-analytics/oauth/start',
    path: '/api/google-analytics/oauth/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleAnalyticsOauthCallbackRoute =
  ApiGoogleAnalyticsOauthCallbackRouteImport.update({
    id: '/api/google-analytics/oauth/callback',
    path: '/api/google-analytics/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sync': typeof ApiSyncRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/jobs/$': typeof JobsSplatRoute
  '/reports/app-store': typeof ReportsAppStoreRoute
  '/reports/churn': typeof ReportsChurnRoute
  '/reports/customers': typeof ReportsCustomersRoute
  '/reports/revenue': typeof ReportsRevenueRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/organizations': typeof SettingsOrganizationsRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/google-analytics/oauth/callback': typeof ApiGoogleAnalyticsOauthCallbackRoute
  '/api/google-analytics/oauth/start': typeof ApiGoogleAnalyticsOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sync': typeof ApiSyncRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/jobs/$': typeof JobsSplatRoute
  '/reports/app-store': typeof ReportsAppStoreRoute
  '/reports/churn': typeof ReportsChurnRoute
  '/reports/customers': typeof ReportsCustomersRoute
  '/reports/revenue': typeof ReportsRevenueRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/organizations': typeof SettingsOrganizationsRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/google-analytics/oauth/callback': typeof ApiGoogleAnalyticsOauthCallbackRoute
  '/api/google-analytics/oauth/start': typeof ApiGoogleAnalyticsOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sync': typeof ApiSyncRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/jobs/$': typeof JobsSplatRoute
  '/reports/app-store': typeof ReportsAppStoreRoute
  '/reports/churn': typeof ReportsChurnRoute
  '/reports/customers': typeof ReportsCustomersRoute
  '/reports/revenue': typeof ReportsRevenueRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/organizations': typeof SettingsOrganizationsRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/google-analytics/oauth/callback': typeof ApiGoogleAnalyticsOauthCallbackRoute
  '/api/google-analytics/oauth/start': typeof ApiGoogleAnalyticsOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/dashboard'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/api/health'
    | '/api/sync'
    | '/apps/$appId'
    | '/jobs/$'
    | '/reports/app-store'
    | '/reports/churn'
    | '/reports/customers'
    | '/reports/revenue'
    | '/settings/connections'
    | '/settings/organizations'
    | '/shops/$shopId'
    | '/api/auth/$'
    | '/api/google-analytics/oauth/callback'
    | '/api/google-analytics/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/dashboard'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/api/health'
    | '/api/sync'
    | '/apps/$appId'
    | '/jobs/$'
    | '/reports/app-store'
    | '/reports/churn'
    | '/reports/customers'
    | '/reports/revenue'
    | '/settings/connections'
    | '/settings/organizations'
    | '/shops/$shopId'
    | '/api/auth/$'
    | '/api/google-analytics/oauth/callback'
    | '/api/google-analytics/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/dashboard'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/api/health'
    | '/api/sync'
    | '/apps/$appId'
    | '/jobs/$'
    | '/reports/app-store'
    | '/reports/churn'
    | '/reports/customers'
    | '/reports/revenue'
    | '/settings/connections'
    | '/settings/organizations'
    | '/shops/$shopId'
    | '/api/auth/$'
    | '/api/google-analytics/oauth/callback'
    | '/api/google-analytics/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSyncRoute: typeof ApiSyncRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
  ReportsAppStoreRoute: typeof ReportsAppStoreRoute
  ReportsChurnRoute: typeof ReportsChurnRoute
  ReportsCustomersRoute: typeof ReportsCustomersRoute
  ReportsRevenueRoute: typeof ReportsRevenueRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsOrganizationsRoute: typeof SettingsOrganizationsRoute
  ShopsShopIdRoute: typeof ShopsShopIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGoogleAnalyticsOauthCallbackRoute: typeof ApiGoogleAnalyticsOauthCallbackRoute
  ApiGoogleAnalyticsOauthStartRoute: typeof ApiGoogleAnalyticsOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organizations': {
      id: '/settings/organizations'
      path: '/settings/organizations'
      fullPath: '/settings/organizations'
      preLoaderRoute: typeof SettingsOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/revenue': {
      id: '/reports/revenue'
      path: '/reports/revenue'
      fullPath: '/reports/revenue'
      preLoaderRoute: typeof ReportsRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/customers': {
      id: '/reports/customers'
      path: '/reports/customers'
      fullPath: '/reports/customers'
      preLoaderRoute: typeof ReportsCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/churn': {
      id: '/reports/churn'
      path: '/reports/churn'
      fullPath: '/reports/churn'
      preLoaderRoute: typeof ReportsChurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/app-store': {
      id: '/reports/app-store'
      path: '/reports/app-store'
      fullPath: '/reports/app-store'
      preLoaderRoute: typeof ReportsAppStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$': {
      id: '/jobs/$'
      path: '/$'
      fullPath: '/jobs/$'
      preLoaderRoute: typeof JobsSplatRouteImport
      parentRoute: typeof JobsRoute
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-analytics/oauth/start': {
      id: '/api/google-analytics/oauth/start'
      path: '/api/google-analytics/oauth/start'
      fullPath: '/api/google-analytics/oauth/start'
      preLoaderRoute: typeof ApiGoogleAnalyticsOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-analytics/oauth/callback': {
      id: '/api/google-analytics/oauth/callback'
      path: '/api/google-analytics/oauth/callback'
      fullPath: '/api/google-analytics/oauth/callback'
      preLoaderRoute: typeof ApiGoogleAnalyticsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JobsRouteChildren {
  JobsSplatRoute: typeof JobsSplatRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsSplatRoute: JobsSplatRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSyncRoute: ApiSyncRoute,
  AppsAppIdRoute: AppsAppIdRoute,
  ReportsAppStoreRoute: ReportsAppStoreRoute,
  ReportsChurnRoute: ReportsChurnRoute,
  ReportsCustomersRoute: ReportsCustomersRoute,
  ReportsRevenueRoute: ReportsRevenueRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsOrganizationsRoute: SettingsOrganizationsRoute,
  ShopsShopIdRoute: ShopsShopIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGoogleAnalyticsOauthCallbackRoute: ApiGoogleAnalyticsOauthCallbackRoute,
  ApiGoogleAnalyticsOauthStartRoute: ApiGoogleAnalyticsOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
